version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/vocabulary
      - ./src:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend-network

    tty: true
    stdin_open: true

networks:
  frontend-network:
    driver: bridge
