version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./vocabulary:/app/vocabulary
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend-network
    tty: true
    stdin_open: true

networks:
  frontend-network:
    driver: bridge
